modLoader="javafml" 
loaderVersion="[28,)" 

[[mods]] 
modId="bizarremod" 
version="0.1.0"
displayName="Wynd's Bizarre Mod" 
credits="Big thanks to FGpisces for his textures, all our patreons for supporting us and every single one of you who downloaded and played this mod" 
authors="Wynd, FGpisces" 
description='''
A PvP focused mod that implementes only the Stands from the popular anime/manga JoJo's Bizarre Adventure
'''

[[dependencies.bizarremod]]
    modId="forge"  
    mandatory=true    
    versionRange="[28,)"    
    ordering="NONE"   
    side="BOTH"

[[dependencies.bizarremod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"
