package xyz.pixelatedw.bizarremod.models;

import net.minecraft.client.renderer.entity.model.BipedModel;
import net.minecraft.client.renderer.entity.model.RendererModel;
import xyz.pixelatedw.bizarremod.entities.stands.GenericStandEntity;

public class AerosmithModel extends BipedModel<GenericStandEntity>
{
	public RendererModel body;
	public RendererModel body_back;
	public RendererModel body_detail_1;
	public RendererModel body_detail_2;
	public RendererModel body_detail_3;
	public RendererModel cockpit;
	public RendererModel front_left_wing_support;
	public RendererModel bomb_support;
	public RendererModel propeller_support;
	public RendererModel front_right_wing_support;
	public RendererModel tail;
	public RendererModel back_left_wings_support;
	public RendererModel back_right_wings_support;
	public RendererModel tail_detail_1;
	public RendererModel back_left_wings_lower;
	public RendererModel back_left_wings_upper;
	public RendererModel back_left_wings_lower_tip;
	public RendererModel back_left_wings_upper_corner;
	public RendererModel back_left_wings_lower_corner_tip;
	public RendererModel back_right_wings_lower;
	public RendererModel back_right_wings_upper;
	public RendererModel back_right_wings_lower_tip;
	public RendererModel back_right_wings_upper_corner;
	public RendererModel back_right_wings_lower_corner_tip;
	public RendererModel cockpit_top;
	public RendererModel front_left_wing_1;
	public RendererModel front_left_wing_2;
	public RendererModel front_left_wing_gun;
	public RendererModel front_left_wing_tip;
	public RendererModel front_left_wing_gun_support;
	public RendererModel bomb;
	public RendererModel bomb_detail_1;
	public RendererModel bomb_detail_1_1;
	public RendererModel bomb_detail_3;
	public RendererModel propeller_1;
	public RendererModel propeller_2;
	public RendererModel front_right_wing_1;
	public RendererModel front_right_wing_2;
	public RendererModel front_right_wing_gun;
	public RendererModel front_right_wing_tip;
	public RendererModel front_right_wing_gun_support;

	public AerosmithModel()
	{
		this.textureWidth = 64;
		this.textureHeight = 64;
		this.front_right_wing_support = new RendererModel(this, 22, 36);
		this.front_right_wing_support.setRotationPoint(-2.5F, 1.0F, -1.2F);
		this.front_right_wing_support.addBox(-1.0F, -1.0F, -1.5F, 2, 2, 3, 0.0F);
		this.setRotateAngle(front_right_wing_support, 0.0F, 0.0F, 0.7853981633974483F);
		this.front_right_wing_gun_support = new RendererModel(this, 0, 22);
		this.front_right_wing_gun_support.setRotationPoint(-0.8F, 0.0F, 1.8F);
		this.front_right_wing_gun_support.addBox(-1.0F, -1.0F, -1.5F, 1, 1, 1, 0.0F);
		this.bomb_detail_3 = new RendererModel(this, 15, 50);
		this.bomb_detail_3.setRotationPoint(0.0F, 0.0F, -3.1F);
		this.bomb_detail_3.addBox(-0.5F, -0.5F, -0.5F, 1, 1, 1, 0.0F);
		this.body_detail_3 = new RendererModel(this, 48, 26);
		this.body_detail_3.setRotationPoint(0.0F, 0.5F, 7.0F);
		this.body_detail_3.addBox(-2.5F, -1.5F, -1.5F, 5, 3, 3, 0.0F);
		this.setRotateAngle(body_detail_3, 0.7853981633974483F, 0.0F, 0.0F);
		this.propeller_2 = new RendererModel(this, 36, 0);
		this.propeller_2.setRotationPoint(0.0F, 0.0F, 0.0F);
		this.propeller_2.addBox(-6.5F, -0.5F, 0.3F, 6, 2, 1, 0.0F);
		this.front_left_wing_2 = new RendererModel(this, 43, 36);
		this.front_left_wing_2.setRotationPoint(-2.5F, -5.3F, 0.0F);
		this.front_left_wing_2.addBox(-1.0F, -1.0F, -1.5F, 1, 6, 3, 0.0F);
		this.setRotateAngle(front_left_wing_2, 0.0F, 0.0F, -0.5235987755982988F);
		this.front_left_wing_gun_support = new RendererModel(this, 0, 22);
		this.front_left_wing_gun_support.setRotationPoint(-0.7F, 0.0F, 1.8F);
		this.front_left_wing_gun_support.addBox(-1.0F, -1.0F, -1.5F, 1, 1, 1, 0.0F);
		this.body_detail_2 = new RendererModel(this, 0, 35);
		this.body_detail_2.setRotationPoint(0.0F, 0.0F, 0.0F);
		this.body_detail_2.addBox(-2.0F, 2.0F, -5.7F, 4, 1, 12, 0.0F);
		this.tail_detail_1 = new RendererModel(this, 50, 17);
		this.tail_detail_1.setRotationPoint(0.0F, -1.0F, 13.6F);
		this.tail_detail_1.addBox(-1.0F, -1.0F, -1.0F, 2, 2, 2, 0.0F);
		this.setRotateAngle(tail_detail_1, 0.7853981633974483F, 0.0F, 0.0F);
		this.propeller_1 = new RendererModel(this, 36, 0);
		this.propeller_1.setRotationPoint(0.0F, 0.0F, 0.0F);
		this.propeller_1.addBox(0.5F, -1.5F, 0.3F, 6, 2, 1, 0.0F);
		this.back_left_wings_lower_corner_tip = new RendererModel(this, 23, 9);
		this.back_left_wings_lower_corner_tip.setRotationPoint(0.0F, 2.5F, 0.0F);
		this.back_left_wings_lower_corner_tip.addBox(-0.5F, -0.5F, -1.0F, 1, 1, 2, 0.0F);
		this.setRotateAngle(back_left_wings_lower_corner_tip, 0.0F, 0.0F, 0.7853981633974483F);
		this.cockpit = new RendererModel(this, 0, 49);
		this.cockpit.setRotationPoint(0.0F, -4.4F, 0.5F);
		this.cockpit.addBox(-1.5F, 0.0F, -2.0F, 3, 2, 5, 0.0F);
		this.body = new RendererModel(this, 0, 0);
		this.body.setRotationPoint(0.0F, 0.0F, 0.0F);
		this.body.addBox(-2.5F, -2.5F, -6.0F, 5, 5, 13, 0.0F);
		this.back_left_wings_lower = new RendererModel(this, 24, 4);
		this.back_left_wings_lower.setRotationPoint(0.0F, 0.0F, 0.0F);
		this.back_left_wings_lower.addBox(1.2F, 0.5F, -1.0F, 6, 1, 2, 0.0F);
		this.setRotateAngle(back_left_wings_lower, 0.0F, 0.0F, -1.1344640137963142F);
		this.cockpit_top = new RendererModel(this, 0, 57);
		this.cockpit_top.setRotationPoint(0.0F, 0.0F, 0.0F);
		this.cockpit_top.addBox(-1.0F, -1.3F, -1.5F, 2, 2, 4, 0.0F);
		this.back_right_wings_lower_corner_tip = new RendererModel(this, 23, 9);
		this.back_right_wings_lower_corner_tip.setRotationPoint(0.0F, 2.5F, 0.0F);
		this.back_right_wings_lower_corner_tip.addBox(-0.5F, -0.5F, -1.0F, 1, 1, 2, 0.0F);
		this.setRotateAngle(back_right_wings_lower_corner_tip, 0.0F, 0.0F, 0.7853981633974483F);
		this.bomb_support = new RendererModel(this, 0, 21);
		this.bomb_support.setRotationPoint(0.5F, 2.7F, -3.0F);
		this.bomb_support.addBox(-1.0F, 0.0F, 0.0F, 1, 2, 2, 0.0F);
		this.bomb_detail_1 = new RendererModel(this, 20, 50);
		this.bomb_detail_1.setRotationPoint(1.5F, 0.0F, 1.4F);
		this.bomb_detail_1.addBox(-0.5F, -0.5F, -1.0F, 1, 1, 2, 0.0F);
		this.front_left_wing_support = new RendererModel(this, 22, 36);
		this.front_left_wing_support.setRotationPoint(2.5F, 1.0F, -1.2F);
		this.front_left_wing_support.addBox(-1.0F, -1.0F, -1.5F, 2, 2, 3, 0.0F);
		this.setRotateAngle(front_left_wing_support, 0.0F, 0.0F, 0.7853981633974483F);
		this.back_left_wings_support = new RendererModel(this, 54, 36);
		this.back_left_wings_support.setRotationPoint(1.5F, -2.3F, 9.0F);
		this.back_left_wings_support.addBox(0.0F, -1.0F, -1.0F, 2, 2, 2, 0.0F);
		this.setRotateAngle(back_left_wings_support, 0.0F, 0.0F, 1.0471975511965976F);
		this.back_left_wings_upper = new RendererModel(this, 38, 9);
		this.back_left_wings_upper.setRotationPoint(0.0F, 0.0F, 0.0F);
		this.back_left_wings_upper.addBox(-0.5F, 0.5F, -1.0F, 8, 1, 2, 0.0F);
		this.setRotateAngle(back_left_wings_upper, 0.0F, 0.0F, -2.6179938779914944F);
		this.back_left_wings_upper_corner = new RendererModel(this, 38, 14);
		this.back_left_wings_upper_corner.setRotationPoint(7.0F, 1.0F, 0.0F);
		this.back_left_wings_upper_corner.addBox(-0.5F, 0.5F, -1.0F, 1, 2, 2, 0.0F);
		this.tail = new RendererModel(this, 41, 20);
		this.tail.setRotationPoint(0.0F, 0.0F, 0.0F);
		this.tail.addBox(-1.0F, -2.0F, 11.0F, 2, 2, 3, 0.0F);
		this.bomb = new RendererModel(this, 20, 49);
		this.bomb.setRotationPoint(-0.5F, 2.0F, 1.3F);
		this.bomb.addBox(-1.0F, -1.0F, -3.0F, 2, 2, 6, 0.0F);
		this.back_left_wings_lower_tip = new RendererModel(this, 23, 9);
		this.back_left_wings_lower_tip.setRotationPoint(7.0F, 1.0F, 0.0F);
		this.back_left_wings_lower_tip.addBox(-0.5F, -0.5F, -1.0F, 1, 1, 2, 0.0F);
		this.setRotateAngle(back_left_wings_lower_tip, 0.0F, 0.0F, 0.7853981633974483F);
		this.propeller_support = new RendererModel(this, 51, 0);
		this.propeller_support.setRotationPoint(0.0F, 0.0F, -7.6F);
		this.propeller_support.addBox(-2.0F, -2.0F, 0.0F, 4, 4, 2, 0.0F);
		this.bomb_detail_1_1 = new RendererModel(this, 20, 50);
		this.bomb_detail_1_1.setRotationPoint(-1.5F, 0.0F, 1.4F);
		this.bomb_detail_1_1.addBox(-0.5F, -0.5F, -1.0F, 1, 1, 2, 0.0F);
		this.back_right_wings_lower = new RendererModel(this, 24, 4);
		this.back_right_wings_lower.setRotationPoint(0.0F, 0.0F, 0.0F);
		this.back_right_wings_lower.addBox(1.2F, 0.5F, -1.0F, 6, 1, 2, 0.0F);
		this.setRotateAngle(back_right_wings_lower, 0.0F, 0.0F, -1.1344640137963142F);
		this.back_right_wings_upper = new RendererModel(this, 38, 9);
		this.back_right_wings_upper.setRotationPoint(0.0F, 0.0F, 0.0F);
		this.back_right_wings_upper.addBox(-0.5F, 0.5F, -1.0F, 8, 1, 2, 0.0F);
		this.setRotateAngle(back_right_wings_upper, 0.0F, 0.0F, -2.6179938779914944F);
		this.back_right_wings_lower_tip = new RendererModel(this, 23, 9);
		this.back_right_wings_lower_tip.setRotationPoint(7.0F, 1.0F, 0.0F);
		this.back_right_wings_lower_tip.addBox(-0.5F, -0.5F, -1.0F, 1, 1, 2, 0.0F);
		this.setRotateAngle(back_right_wings_lower_tip, 0.0F, 0.0F, 0.7853981633974483F);
		this.front_right_wing_1 = new RendererModel(this, 33, 36);
		this.front_right_wing_1.setRotationPoint(-1.3F, 3.3F, 0.0F);
		this.front_right_wing_1.addBox(-1.0F, -3.0F, -1.5F, 1, 4, 3, 0.0F);
		this.setRotateAngle(front_right_wing_1, 0.0F, 0.0F, 0.5235987755982988F);
		this.body_back = new RendererModel(this, 23, 20);
		this.body_back.setRotationPoint(0.0F, 0.0F, 0.0F);
		this.body_back.addBox(-2.5F, -2.5F, 7.0F, 5, 3, 4, 0.0F);
		this.front_left_wing_1 = new RendererModel(this, 33, 36);
		this.front_left_wing_1.setRotationPoint(3.4F, -1.3F, 0.0F);
		this.front_left_wing_1.addBox(-1.0F, -1.0F, -1.5F, 1, 4, 3, 0.0F);
		this.setRotateAngle(front_left_wing_1, 0.0F, 0.0F, 1.0471975511965976F);
		this.front_right_wing_gun = new RendererModel(this, 0, 27);
		this.front_right_wing_gun.setRotationPoint(1.3F, 1.8F, -0.5F);
		this.front_right_wing_gun.addBox(-1.0F, -1.0F, -1.5F, 1, 1, 4, 0.0F);
		this.setRotateAngle(front_right_wing_gun, 0.0F, 0.0F, 0.2617993877991494F);
		this.body_detail_1 = new RendererModel(this, 0, 18);
		this.body_detail_1.setRotationPoint(0.0F, 0.0F, 0.0F);
		this.body_detail_1.addBox(-2.0F, -3.0F, -5.5F, 4, 1, 15, 0.0F);
		this.front_left_wing_gun = new RendererModel(this, 0, 27);
		this.front_left_wing_gun.setRotationPoint(1.5F, -1.0F, -0.5F);
		this.front_left_wing_gun.addBox(-1.0F, -1.0F, -1.5F, 1, 1, 4, 0.0F);
		this.setRotateAngle(front_left_wing_gun, 0.0F, 0.0F, -0.2617993877991494F);
		this.front_left_wing_tip = new RendererModel(this, 23, 8);
		this.front_left_wing_tip.setRotationPoint(-0.5F, -0.9F, 0.0F);
		this.front_left_wing_tip.addBox(-0.5F, -0.5F, -1.5F, 1, 1, 3, 0.0F);
		this.setRotateAngle(front_left_wing_tip, 0.0F, 0.0F, 0.6981317007977318F);
		this.front_right_wing_2 = new RendererModel(this, 43, 36);
		this.front_right_wing_2.setRotationPoint(-0.5F, 1.8F, 0.0F);
		this.front_right_wing_2.addBox(-1.0F, -1.0F, -1.5F, 1, 6, 3, 0.0F);
		this.setRotateAngle(front_right_wing_2, 0.0F, 0.0F, 0.5235987755982988F);
		this.back_right_wings_support = new RendererModel(this, 54, 36);
		this.back_right_wings_support.setRotationPoint(-1.5F, -2.3F, 9.0F);
		this.back_right_wings_support.addBox(0.0F, -1.0F, -1.0F, 2, 2, 2, 0.0F);
		this.setRotateAngle(back_right_wings_support, 0.0F, 3.141592653589793F, -1.0471975511965976F);
		this.back_right_wings_upper_corner = new RendererModel(this, 38, 14);
		this.back_right_wings_upper_corner.setRotationPoint(7.0F, 1.0F, 0.0F);
		this.back_right_wings_upper_corner.addBox(-0.5F, 0.5F, -1.0F, 1, 2, 2, 0.0F);
		this.front_right_wing_tip = new RendererModel(this, 23, 8);
		this.front_right_wing_tip.setRotationPoint(-0.5F, 5.0F, 0.0F);
		this.front_right_wing_tip.addBox(-0.5F, -0.5F, -1.5F, 1, 1, 3, 0.0F);
		this.setRotateAngle(front_right_wing_tip, 0.0F, 0.0F, 0.6981317007977318F);
		this.body.addChild(this.front_right_wing_support);
		this.front_right_wing_gun.addChild(this.front_right_wing_gun_support);
		this.bomb.addChild(this.bomb_detail_3);
		this.body.addChild(this.body_detail_3);
		this.propeller_support.addChild(this.propeller_2);
		this.front_left_wing_1.addChild(this.front_left_wing_2);
		this.front_left_wing_gun.addChild(this.front_left_wing_gun_support);
		this.body.addChild(this.body_detail_2);
		this.tail.addChild(this.tail_detail_1);
		this.propeller_support.addChild(this.propeller_1);
		this.back_left_wings_upper_corner.addChild(this.back_left_wings_lower_corner_tip);
		this.body.addChild(this.cockpit);
		this.back_left_wings_support.addChild(this.back_left_wings_lower);
		this.cockpit.addChild(this.cockpit_top);
		this.back_right_wings_upper_corner.addChild(this.back_right_wings_lower_corner_tip);
		this.body.addChild(this.bomb_support);
		this.bomb.addChild(this.bomb_detail_1);
		this.body.addChild(this.front_left_wing_support);
		this.body_back.addChild(this.back_left_wings_support);
		this.back_left_wings_support.addChild(this.back_left_wings_upper);
		this.back_left_wings_upper.addChild(this.back_left_wings_upper_corner);
		this.body_back.addChild(this.tail);
		this.bomb_support.addChild(this.bomb);
		this.back_left_wings_lower.addChild(this.back_left_wings_lower_tip);
		this.body.addChild(this.propeller_support);
		this.bomb.addChild(this.bomb_detail_1_1);
		this.back_right_wings_support.addChild(this.back_right_wings_lower);
		this.back_right_wings_support.addChild(this.back_right_wings_upper);
		this.back_right_wings_lower.addChild(this.back_right_wings_lower_tip);
		this.front_right_wing_support.addChild(this.front_right_wing_1);
		this.body.addChild(this.body_back);
		this.front_left_wing_support.addChild(this.front_left_wing_1);
		this.front_right_wing_1.addChild(this.front_right_wing_gun);
		this.body.addChild(this.body_detail_1);
		this.front_left_wing_1.addChild(this.front_left_wing_gun);
		this.front_left_wing_2.addChild(this.front_left_wing_tip);
		this.front_right_wing_1.addChild(this.front_right_wing_2);
		this.body_back.addChild(this.back_right_wings_support);
		this.back_right_wings_upper.addChild(this.back_right_wings_upper_corner);
		this.front_right_wing_2.addChild(this.front_right_wing_tip);
	}

	@Override
	public void render(GenericStandEntity entity, float limbSwing, float limbSwingAmount, float ageInTicks, float netHeadYaw, float headPitch, float scale)
	{
		this.body.render(scale);
	}

	@Override
	public void setRotationAngles(GenericStandEntity entity, float limbSwing, float limbSwingAmount, float ageInTicks, float netHeadYaw, float headPitch, float scale)
	{
		super.setRotationAngles(entity, limbSwing, limbSwingAmount, ageInTicks, netHeadYaw, headPitch, scale);

		this.propeller_support.rotateAngleZ += 0.5;
	}

	public void setRotateAngle(RendererModel RendererModel, float x, float y, float z)
	{
		RendererModel.rotateAngleX = x;
		RendererModel.rotateAngleY = y;
		RendererModel.rotateAngleZ = z;
	}
}
